export const CONSTANT_MESSAGE = {
  STATUS: {
    SUCCESS: "success",
    ERROR: "error",
  },
  AUTH: {
    AUTHENTICATION_SUCCESS: "Authentication success",
    AUTHENTICATION_FAILED: "Authentication failed",
    INTERNAL_SERVER_ERROR: "Internal server error",
    TOKEN_NOT_PROVIDED: "Token not provided",
    INVALID_TOKEN: "Invalid token",
  },
  MESSAGE: {
    SOMETHING_WENT_WRONG: "Something went wrong",
    SUCCESSFULLY_FETCHED: "Successfully fetched",
  },
  USER: {
    USER_CREATED_SUCCESSFULLY: "User created successfully",
    USER_UPDATED_SUCCESSFULLY: "User updated successfully",
    USER_NAME_ALREADY_EXISTS: "User Name already exists",
    ERROR_CREATING_USER: "Error in creating user",
    ERROR_IN_GETTING_USERS: "Error in getting user(s)",
    NO_USER_FOUND: "No user(s) found!",
    USER_FOUND: "user(s) found!",
    ERROR_IN_UPDATING_USER: "Error in updating user",
    ERROR_IN_DELETING_USER: "Error in deleting user",
    USER_SUCCESSFULLY_DELETED: "User successfully deleted",
  },
  ADMIN: {
    ADMIN_CREATED_SUCCESSFULLY: "Admin created successfully",
    ADMIN_UPDATED_SUCCESSFULLY: "Admin updated successfully",
    ADMIN_NAME_ALREADY_EXISTS: "Admin Name already exists",
    ERROR_CREATING_ADMIN: "Error in creating admin",
    ERROR_IN_GETTING_ADMINS: "Error in getting admin(s)",
    NO_ADMIN_FOUND: "No admin(s) found!",
    ADMIN_FOUND: "admin(s) found!",
    ERROR_IN_UPDATING_ADMIN: "Error in updating admin",
    ERROR_IN_DELETING_ADMIN: "Error in deleting admin",
    ADMIN_SUCCESSFULLY_DELETED: "Admin successfully deleted",
  },
  BOOK: {
    BOOK_CREATED_SUCCESSFULLY: "Book created successfully",
    BOOK_UPDATED_SUCCESSFULLY: "Book updated successfully",
    BOOK_NAME_ALREADY_EXISTS: "Book Name already exists",
    ERROR_CREATING_BOOK: "Error in creating book",
    ERROR_IN_GETTING_BOOKS: "Error in getting book(s)",
    NO_BOOK_FOUND: "No book(s) found!",
    BOOK_FOUND: "book(s) found!",
    ERROR_IN_UPDATING_BOOK: "Error in updating book",
    BOOK_SUCCESSFULLY_DELETED: "Book successfully deleted",
  },
  TRANSACTION: {
    TRANSACTION_CREATED_SUCCESSFULLY: "Transaction created successfully",
    TRANSACTION_UPDATED_SUCCESSFULLY: "Transaction updated successfully",
    TRANSACTION_ALREADY_EXISTS: "Transaction already exists",
    ERROR_CREATING_TRANSACTION: "Error in creating transaction",
    ERROR_IN_GETTING_TRANSACTIONS: "Error in getting transaction(s)",
    NO_TRANSACTION_FOUND: "No transaction(s) found!",
    TRANSACTION_FOUND: "transaction(s) found!",
    ERROR_IN_UPDATING_TRANSACTION: "Error in updating transaction",
    TRANSACTION_SUCCESSFULLY_DELETED: "Transaction successfully deleted",
  },
  ERROR: {
    VALIDATION_ERROR: "Validation error",
    ID_IS_REQUIRED: "Id id required",
    INVALID_CREDENTIALS: "Invalid Credentials",
    INCORRECT_PASSWORD: "Incorrect password",
    PLEASE_PROVIDE_A_VALID_NAME: "Please provide a valid name.",
  },
};
